#!/usr/bin/env python3
"""Regenerate zubi-data.js from journeys.html canon + the homepage SYN map.

Run after any change to journeys.html prices/nights/tags so Zubi never drifts
from the catalogue. Zubi holds no facts of its own: every journey, price and
night count comes from here; every company fact comes from the CONFIRMED list
in zubi-chat.js.

    python3 tools/build-zubi-data.py
"""
import html, json, re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(ROOT, 'journeys.html'), encoding='utf-8').read()
home = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()

cards = re.findall(r'<article class="jcard"(.*?)</article>', src, re.S)
out = []
for c in cards:
    def attr(n):
        m = re.search(r'\bdata-%s="([^"]*)"' % n, c)
        return html.unescape(m.group(1)) if m else ''
    href = re.search(r'<a class="jhit" href="([^"]+)"', c).group(1)
    img = re.search(r'<img src="([^"]+)"', c).group(1)
    attrs = re.search(r'<div class="jattrs">(.*?)</div>', c, re.S)
    spans = re.findall(r'</svg> ([^<]+)</span>', attrs.group(1)) if attrs else []
    spans = [html.unescape(x).strip() for x in spans]
    place = spans[1] if len(spans) > 1 else ''
    pace = spans[2] if len(spans) > 2 else ''
    desc = re.search(r'</div><p>(.*?)</p><div class="jfoot">', c, re.S)
    tags = [t for t in attr('tags').split('|') if t]
    out.append({
        'h': href, 't': attr('title'), 'g': img,
        'n': int(attr('n') or 0), 'p': int(attr('p') or 0),
        'r': place, 'pace': pace,
        'season': attr('season').replace('&ndash;', '–'),
        'tags': tags,
        'k': (attr('blob') + ' ' + place.lower()).strip(),
        'd': html.unescape(re.sub(r'<[^>]+>', '', desc.group(1))).strip() if desc else '',
    })

m = re.search(r'var SYN=(\{.*?\});', home, re.S)
syn_src = m.group(1)
# The homepage SYN object uses unquoted keys; make it JSON.
syn_json = re.sub(r'([{,])\s*([a-zA-Z0-9_]+)\s*:', r'\1"\2":', syn_src).replace("'", '"')
SYN = json.loads(syn_json)

js = ('/* GENERATED by tools/build-zubi-data.py from journeys.html canon — do not hand-edit. */\n'
      'window.ZUBI_DATA=' + json.dumps({'journeys': out, 'syn': SYN}, ensure_ascii=False, separators=(',', ':')) + ';\n')
open(os.path.join(ROOT, 'zubi-data.js'), 'w', encoding='utf-8').write(js)
missing = [j['t'] for j in out if not j['p']]
print('journeys:', len(out), '| syn:', len(SYN), '| zero-price:', missing or 'none')
